/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/r38JCZugy3m
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function JobBoardComponent() {
  return (
    <div className="w-full">
      <div className="container grid max-w-full gap-6 px-4 py-6 lg:gap-10 lg:px-6 lg:py-12">
        <div className="space-y-6">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">
              Find your dream job
            </h1>
            <p className="border max-w-5xl text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Search for jobs and internships. Discover the companies and roles
              that are right for you.
            </p>
          </div>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="search">Search</Label>
              <Input
                id="search"
                placeholder="Search for jobs, companies, locations"
              />
            </div>
            <div className="flex items-center space-x-2">
              <Button variant="outline">Search</Button>
            </div>
            <p className="text-sm text-muted-foreground">1,999 jobs</p>
          </div>
        </div>
      </div>
    </div>
  );
}
