/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gvFNcDOvSTa
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import Link from "next/link";
import Image from "next/image";

export function JobList() {
  return (
    <div className="w-full space-y-6">
      <div className="container grid max-w-full gap-6 px-4 py-6 lg:gap-10 lg:px-6 lg:py-12">
        <div className="grid gap-6">
          <Card>
            <CardContent className="grid gap-4">
              <div>
                <h3 className="text-2xl font-bold">
                  Senior Frontend Developer
                </h3>
                <p className="text-gray-500 dark:text-gray-400">Engineering</p>
              </div>
              <div className="grid gap-2">
                <div>
                  <h4 className="font-semibold">Location</h4>
                  <p>New York, NY</p>
                </div>
                <div>
                  <h4 className="font-semibold">Employment Type</h4>
                  <p>Full-time</p>
                </div>
              </div>
              <div>
                <h4 className="font-semibold">Description</h4>
                <p className="text-gray-500 dark:text-gray-400">
                  We are looking for a talented and experienced Senior Frontend
                  Developer to join our team. You will be responsible for
                  designing, implementing, and maintaining the user interfaces
                  of our web applications.
                </p>
              </div>
            </CardContent>
            <CardFooter>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <img
                    src="/placeholder.svg"
                    width="40"
                    height="40"
                    alt="Company logo"
                    className="rounded-full"
                  />
                  <div className="text-sm font-medium">
                    <h4>Acme Inc</h4>
                    <p className="text-xs text-gray-500 dark:text-gray-400">
                      We&apos;re on a mission to make the web more accessible.
                    </p>
                  </div>
                </div>
                <Link
                  href="#"
                  className="inline-flex h-9 items-center justify-center rounded-md bg-gray-100 px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-950/50 dark:hover:text-gray-50 dark:transition-colors"
                  prefetch={false}
                >
                  Apply
                </Link>
              </div>
            </CardFooter>
          </Card>
          <Card>
            <CardContent className="grid gap-4">
              <div>
                <h3 className="text-2xl font-bold">Product Manager</h3>
                <p className="text-gray-500 dark:text-gray-400">Product</p>
              </div>
              <div className="grid gap-2">
                <div>
                  <h4 className="font-semibold">Location</h4>
                  <p>San Francisco, CA</p>
                </div>
                <div>
                  <h4 className="font-semibold">Employment Type</h4>
                  <p>Full-time</p>
                </div>
              </div>
              <div>
                <h4 className="font-semibold">Description</h4>
                <p className="text-gray-500 dark:text-gray-400">
                  We are looking for an experienced Product Manager to lead the
                  development of our next-generation platform. The ideal
                  candidate is a strategic thinker with a passion for creating
                  innovative and user-friendly products.
                </p>
              </div>
            </CardContent>
            <CardFooter>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <Image
                    src="/placeholder.svg"
                    width="40"
                    height="40"
                    alt="Company logo"
                    className="rounded-full"
                  />
                  <div className="text-sm font-medium">
                    <h4>Acme Inc</h4>
                    <p className="text-xs text-gray-500 dark:text-gray-400">
                      We&apos;re on a mission to make the web more accessible.
                    </p>
                  </div>
                </div>
                <Link
                  href="#"
                  className="inline-flex h-9 items-center justify-center rounded-md bg-gray-100 px-4 py-2 text-sm font-medium transition-colors hover:bg-gray-100/50 dark:bg-gray-950 dark:hover:bg-gray-950/50 dark:hover:text-gray-50 dark:transition-colors"
                  prefetch={false}
                >
                  Apply
                </Link>
              </div>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>
  );
}
