/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EZ4TXszeDxZ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import SVG from "@/public/placeholder.svg";
import Logo from "@/public/unibui.png";
import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Card,
  CardHeader,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export function TestComponent() {
  const [savedJobs, setSavedJobs] = useState([]);
  const handleSaveJob = (job) => {
    if (!savedJobs.some((j) => j.id === job.id)) {
      setSavedJobs([...savedJobs, job]);
      localStorage.setItem("savedJobs", JSON.stringify([...savedJobs, job]));
    }
  };
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-background border-b px-4 md:px-6 flex items-center h-16 shrink-0">
        <Link href="#" className="flex items-center gap-2 " prefetch={false}>
          <Image src={Logo} width={90} height={90} alt="Unibui Company Logo" />
          <span className="mt-1 p-3 text-sm italic underline underline-offset-4">
            job board
          </span>
        </Link>
        <nav className="ml-auto flex items-center gap-6 text-sm font-medium hidden md:flex">
          <Link
            href="/"
            className="hover:underline underline-offset-4"
            prefetch={false}
          >
            Browse Jobs
          </Link>
        </nav>
        <Button variant="ghost" size="icon" className="ml-auto md:hidden">
          <MenuIcon className="w-6 h-6" />
          <span className="sr-only">Toggle menu</span>
        </Button>
      </header>
      <Tabs defaultValue="account" className="m-6">
        <TabsList className="gap-9 mb-4 ">
          <TabsTrigger value="account">Browse</TabsTrigger>
          <TabsTrigger value="password">Saved</TabsTrigger>
          <TabsTrigger value="applied">Applied</TabsTrigger>
        </TabsList>
        <TabsContent
          className="border border-red-500 min-h-screen"
          value="account"
        >
          Make changes to your account here.
        </TabsContent>
        <TabsContent value="password">Change your password here.</TabsContent>
        <TabsContent value="applied">Job applied.</TabsContent>
      </Tabs>

      <main className="flex-1 py-8 px-4 md:px-6">
        <div className="max-w-3xl mx-auto">
          <form className="bg-background border rounded-lg p-4 flex items-center gap-4 mb-8">
            <SearchIcon className="w-5 h-5 text-muted-foreground" />
            <Input
              type="search"
              placeholder="Search for jobs..."
              className="flex-1 border-none focus:ring-0"
            />
            <Button className="shrink-0 hidden sm:inline-flex">Search</Button>
            <Button className="shrink-0 sm:hidden">
              <SearchIcon className="w-5 h-5" />
              <span className="sr-only">Search</span>
            </Button>
          </form>
          <div className="grid gap-8">
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Image
                      src={SVG}
                      width={40}
                      height={40}
                      alt="Company Logo"
                      className="rounded-full"
                    />
                    <div>
                      <div className="font-medium">Acme Inc.</div>
                      <div className="text-sm text-muted-foreground">
                        San Francisco, CA
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge
                          variant="secondary"
                          className="bg-green-500 text-white"
                        >
                          Remote
                        </Badge>
                        <Badge
                          variant="secondary"
                          className="bg-blue-500 text-white"
                        >
                          Full-time
                        </Badge>
                        <Badge
                          variant="secondary"
                          className="bg-yellow-500 text-white"
                        >
                          High Salary
                        </Badge>
                      </div>
                    </div>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="flex flex-col gap-2">
                  <h3 className="text-lg font-semibold">
                    Senior Software Engineer
                  </h3>
                  <p className="text-muted-foreground line-clamp-2">
                    We are looking for an experienced software engineer to join
                    our team and help us build innovative products. You will be
                    responsible for designing, developing, and maintaining
                    complex software systems.
                  </p>
                  <div className="flex items-center gap-4 text-sm text-muted-foreground">
                    <div>$120k - $150k</div>
                    <Separator
                      orientation="vertical"
                      className="hidden sm:inline-flex"
                    />
                    <div>3+ years experience</div>
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Button
                  className="w-full flex items-center justify-center"
                  onClick={() =>
                    handleSaveJob({
                      id: 1,
                      title: "Senior Software Engineer",
                      company: "Acme Inc.",
                    })
                  }
                >
                  <CloudLightningIcon className="mr-2 h-4 w-4" />
                  Fast Apply
                </Button>
                <Button
                  variant="outline"
                  className="w-full "
                  onClick={() =>
                    handleSaveJob({
                      id: 1,
                      title: "Senior Software Engineer",
                      company: "Acme Inc.",
                    })
                  }
                >
                  Save Job
                </Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <img
                      src="/placeholder.svg"
                      width={40}
                      height={40}
                      alt="Company Logo"
                      className="rounded-full"
                    />
                    <div>
                      <div className="font-medium">Globex Corp.</div>
                      <div className="text-sm text-muted-foreground">
                        New York, NY
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge
                          variant="secondary"
                          className="bg-green-500 text-white"
                        >
                          Remote
                        </Badge>
                        <Badge
                          variant="secondary"
                          className="bg-blue-500 text-white"
                        >
                          Part-time
                        </Badge>
                        <Badge
                          variant="secondary"
                          className="bg-purple-500 text-white"
                        >
                          Flexible Schedule
                        </Badge>
                      </div>
                    </div>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="flex flex-col gap-2">
                  <h3 className="text-lg font-semibold">Frontend Developer</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    We are looking for a talented frontend developer to join our
                    growing team. You will be responsible for building
                    high-performance, responsive web applications using the
                    latest technologies.
                  </p>
                  <div className="flex items-center gap-4 text-sm text-muted-foreground">
                    <div>$80k - $100k</div>
                    <Separator
                      orientation="vertical"
                      className="hidden sm:inline-flex"
                    />
                    <div>1-2 years experience</div>
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Button
                  className="w-full flex items-center justify-center"
                  onClick={() =>
                    handleSaveJob({
                      id: 2,
                      title: "Frontend Developer",
                      company: "Globex Corp.",
                    })
                  }
                >
                  <CloudLightningIcon className="mr-2 h-4 w-4" />
                  Fast Apply
                </Button>
                <Button
                  variant="outline"
                  className="w-full "
                  onClick={() =>
                    handleSaveJob({
                      id: 2,
                      title: "Frontend Developer",
                      company: "Globex Corp.",
                    })
                  }
                >
                  Save Job
                </Button>
              </CardFooter>
            </Card>
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <img
                      src="/placeholder.svg"
                      width={40}
                      height={40}
                      alt="Company Logo"
                      className="rounded-full"
                    />
                    <div>
                      <div className="font-medium">Stark Industries</div>
                      <div className="text-sm text-muted-foreground">
                        Los Angeles, CA
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge
                          variant="secondary"
                          className="bg-green-500 text-white"
                        >
                          Remote
                        </Badge>
                        <Badge
                          variant="secondary"
                          className="bg-orange-500 text-white"
                        >
                          Competitive Salary
                        </Badge>
                        <Badge
                          variant="secondary"
                          className="bg-pink-500 text-white"
                        >
                          Equity
                        </Badge>
                      </div>
                    </div>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="flex flex-col gap-2">
                  <h3 className="text-lg font-semibold">Backend Engineer</h3>
                  <p className="text-muted-foreground line-clamp-2">
                    We are seeking an experienced backend engineer to join our
                    team and help us build scalable and secure web services. You
                    will be responsible for designing and implementing robust
                    APIs and database systems.
                  </p>
                  <div className="flex items-center gap-4 text-sm text-muted-foreground">
                    <div>$100k - $130k</div>
                    <Separator
                      orientation="vertical"
                      className="hidden sm:inline-flex"
                    />
                    <div>2-4 years experience</div>
                  </div>
                </div>
              </CardContent>
              <CardFooter>
                <Button
                  className="w-full flex items-center justify-center"
                  onClick={() =>
                    handleSaveJob({
                      id: 3,
                      title: "Backend Engineer",
                      company: "Stark Industries",
                    })
                  }
                >
                  <CloudLightningIcon className="mr-2 h-4 w-4" />
                  Fast Apply
                </Button>
                <Button
                  variant="outline"
                  className="w-full "
                  onClick={() =>
                    handleSaveJob({
                      id: 3,
                      title: "Backend Engineer",
                      company: "Stark Industries",
                    })
                  }
                >
                  Save Job
                </Button>
              </CardFooter>
            </Card>
          </div>
        </div>
      </main>
      <footer className="bg-muted border-t px-4 md:px-6 py-6 text-sm">
        <div className="container max-w-7xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <Link
              href="#"
              className="flex items-center gap-2 font-semibold"
              prefetch={false}
            >
              <BriefcaseIcon className="w-5 h-5" />
              <span>Job Board</span>
            </Link>
            <Separator
              orientation="vertical"
              className="h-5 hidden md:inline-flex"
            />
            <div className="flex flex-col md:flex-row items-center gap-4 md:gap-2">
              <Link
                href="#"
                className="hover:underline underline-offset-4"
                prefetch={false}
              >
                Browse Jobs
              </Link>
              <Link
                href="#"
                className="hover:underline underline-offset-4"
                prefetch={false}
              >
                Post a Job
              </Link>
              <Link
                href="#"
                className="hover:underline underline-offset-4"
                prefetch={false}
              >
                Employers
              </Link>
              <Link
                href="#"
                className="hover:underline underline-offset-4"
                prefetch={false}
              >
                About
              </Link>
            </div>
          </div>
          <div className="flex items-center gap-4 text-muted-foreground">
            <Link
              href="#"
              className="hover:underline underline-offset-4"
              prefetch={false}
            >
              Privacy Policy
            </Link>
            <Link
              href="#"
              className="hover:underline underline-offset-4"
              prefetch={false}
            >
              Terms of Service
            </Link>
            <div>&copy; 2024 Job Board. All rights reserved.</div>
          </div>
        </div>
      </footer>
    </div>
  );
}

function BriefcaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  );
}

function CloudLightningIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 16.326A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 .5 8.973" />
      <path d="m13 12-3 5h4l-3 5" />
    </svg>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
